[package]
name = "day9"
version = "0.1.0"
edition = "2021"

[[bench]]
name = "bench"
harness = false

[[bin]]
name = "day9"
path = "benches/main.rs"

[dependencies]
utils = { path = "../utils" }
criterion = { version = "0.5.1", default-features = false, features = ["html_reports"] }