[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.10.0"
core_affinity = "0.8.1"
criterion = { version = "0.5.1", default-features = false, features = ["html_reports"] }
